site_name: pipen
repo_url: https://github.com/pwwang/pipen
repo_name: pwwang/pipen
theme:
    name: 'material'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi
extra_css:
    - style.css
nav:
    - 'Introduction': 'index.md'
    - 'Basics': 'basics.md'
    - 'Defining a process': 'defining-proc.md'
    - 'Defining and running a pipeline': 'running.md'
    - 'Templating': 'templating.md'
    - 'Channels': 'channels.md'
    - 'Input and output': 'input-output.md'
    - 'Script': 'script.md'
    - 'Caching': 'caching.md'
    - 'Error handling': 'error.md'
    - 'Configurations': 'configurations.md'
    - 'Plugins': 'plugin.md'
    - 'Scheduler': 'scheduler.md'
    - 'Process group': 'proc-group.md'
    - 'Command line iterface': 'cli.md'
    - 'Examples': 'examples.md'
    - 'Change log': 'CHANGELOG.md'
    - 'API': mkapi/api/pipen
