[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "PyPPL"
version = "1.4.3"
description = "A Python PiPeLine framework"
authors = [ "pwwang <pwwang@pwwang.com>",]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pwwang/PyPPL"
repository = "https://github.com/pwwang/PyPPL"

[[tool.poetry.packages]]
include = "pyppl/*.py"

[tool.poetry.dependencies]
python = "^3.5"
python-box = "^3.4.1"
liquidpy = "^0.0.7"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
