[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "PyPPL"
version = "1.4.3"
description = "A Python PiPeLine framework"
authors = [ "pwwang <pwwang@pwwang.com>",]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pwwang/PyPPL"
repository = "https://github.com/pwwang/PyPPL"

[[tool.poetry.packages]]
include = "pyppl/*.py"

[tool.poetry.dependencies]
python = "^3.5"
python-box = "^3.4.1"
liquidpy = "^0.0.7"
pyparam = "^0.1.6"
filelock = "^3.0.0"
python-simpleconf = "^0.1.5"
cmdy = "^0.1.9"
colorama = "^0.4.1"
psutil = "^5.6"
transitions = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
jinja2 = "^2.0.0"
pyyaml = "^5.0.0"
faker = "^1.0.0"
graphviz = "^0.11"
